#from https://github.com/marketplace/actions/fork-sync

name: Sync Fork

on:
  schedule:
    - cron: '*/3000 * * * *' # every 3000 minutes - approx 2.8 days
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: kndm/iati-diff
        with:
          owner: matmaxgeds
          base: master
          head: master
